- package:
  - name: pier-core
  - section:
    - name: library
    - message:
      - name: Weeds exported
      - module:
        - name: Pier.Core.Internal.Directory
        - identifier: SymbolicLink

