version: 2

references:
    build-base: &build-base
      docker:
        - image: judah/pier-ci:v3
      steps:
        - checkout
        - restore_cache:
            keys:
              - stack-cache-v5-{{ arch }}-{{ .Branch }}
              - stack-cache-v5-{{ arch }}-master
        - run:
            command: |
              echo 'export PATH=$HOME/.local/bin:$PATH' >> $BASH_ENV

        # Build with `stack`
        - run: stack --no-terminal install weeder hlint
        - run: stack --no-terminal build --only-dependencies --fast --no-terminal
        - run: stack --no-terminal build --pedantic --fast --no-terminal

        - run: hlint .
        - run: weeder . --build

        - save_cache:
              key: stack-cache-v5-{{ arch }}-{{ .Branch }}-{{ epoch }}
              paths:
                  - ~/.stack
                  - .stack-work

        # Run pier on some sample packages
        - run:
            command: |
              $(stack exec which pier) build -j4 \
                  --keep-going \
                  --pier-yaml=test-package-config.yaml \
                  $(cat .circleci/test-packages.txt)
        - run: $(stack exec which pier) build -j4
        - run: $(stack exec which pier) run -j4 hlint --sandbox $PWD/pier/src
        - run: $(stack exec which pier) run hlint pier/src
        - run: $(stack exec which pier) test split
        - run: $(stack exec which pier) test split:test:split-tests
        - run:
            command: |
                echo "system-ghc: true" >> example/pier.yaml
        - run: stack exec pier -- build --pier-yaml=example/pier.yaml text unix-compat
        # Test without the shared cache
        # TODO: add more extensive testing
        - run:
            command: |
                PIER="stack exec pier -- --pier-yaml=example/pier.yaml"
                $PIER clean-all
                $PIER build --no-shared-cache network split

jobs:
  build:
    <<: *build-base

workflows:
  version: 2
  build-and-test:
      jobs:
        - build
