name: pier-core
version: 0.2.0.1
license: BSD3
maintainer: judah.jacobson@gmail.com
synopsis: A library for writing forwards-declared build systems in haskell.
description: |
    A library for writing build systems in Haskell, built on top of
    <http://shakebuild.com shake>.

    Pier provides a generic approach to building and caching file outputs.
    It enables build actions to be written in a "forwards" style, which
    generally leads to simpler logic than backwards-defined build systems
    such as make or (normal) Shake, where each step of the build logic must
    be written as a new build rule.

    For more details, see "Pier.Core.Artifact".
category: Development
github: judah/pier

library:
  source-dirs: 'src'
  dependencies:
    - Cabal == 2.2.*
    - base == 4.11.*
    - base64-bytestring == 1.0.*
    - binary == 0.8.*
    - bytestring == 0.10.*
    - containers == 0.5.*
    - cryptohash-sha256 == 0.11.*
    - directory >= 1.3.1 && < 1.4
    - hashable == 1.2.*
    - http-client == 0.5.*
    - http-client-tls == 0.3.*
    - http-types == 0.12.*
    - process == 1.6.*
    - shake >= 0.16.4 && < 0.17
    - temporary == 1.3.*
    - text == 1.2.*
    - unix == 2.7.*
  other-modules:
    - Pier.Core.Directory
    - Pier.Core.HashableSet
  default-extensions: !include ../common-extensions.yaml
